# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
# GitHub Actions
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
  commit-message:
    prefix: ":seedling:"
# Go modules in main branch
- package-ecosystem: "gomod"
  directory: "/"
  schedule:
    interval: "weekly"
  ignore:
    # Ignore controller-runtime as its upgraded manually.
    - dependency-name: "sigs.k8s.io/controller-runtime"
    # Ignore k8s and its transitives modules as they are upgraded manually
    # together with controller-runtime.
    - dependency-name: "k8s.io/*"
    # Ignore wrangler
    - dependency-name: "github.com/rancher/wrangler"
    - dependency-name: "github.com/rancher/wrangler/v3"
    # Ignore rancher apis
    - dependency-name: "github.com/rancher/rancher/pkg/apis"
  commit-message:
    prefix: ":seedling:"
  target-branch: "main"
# Go modules in release-v2.9 branch
- package-ecosystem: "gomod"
  directory: "/"
  schedule:
    interval: "weekly"
  ignore:
    # Ignore controller-runtime as its upgraded manually.
    - dependency-name: "sigs.k8s.io/controller-runtime"
    # Ignore k8s and its transitives modules as they are upgraded manually
    # together with controller-runtime.
    - dependency-name: "k8s.io/*"
    # Ignore wrangler
    - dependency-name: "github.com/rancher/wrangler"
    - dependency-name: "github.com/rancher/wrangler/v3"
    # Ignore rancher apis
    - dependency-name: "github.com/rancher/rancher/pkg/apis"
  commit-message:
    prefix: ":seedling:"
  target-branch: "release-v2.9"
# Go modules in release-v2.8 branch
- package-ecosystem: "gomod"
  directory: "/"
  schedule:
    interval: "weekly"
  ignore:
    # Ignore controller-runtime as its upgraded manually.
    - dependency-name: "sigs.k8s.io/controller-runtime"
    # Ignore k8s and its transitives modules as they are upgraded manually
    # together with controller-runtime.
    - dependency-name: "k8s.io/*"
    # Ignore wrangler
    - dependency-name: "github.com/rancher/wrangler"
    - dependency-name: "github.com/rancher/wrangler/v3"
    # Ignore rancher apis
    - dependency-name: "github.com/rancher/rancher/pkg/apis"
    # Ignore Google API version, due it is breaking integration
    - dependency-name: "google.golang.org/api"
  commit-message:
    prefix: ":seedling:"
  target-branch: "release-v2.8"
# Go modules in release-v2.7 branch
- package-ecosystem: "gomod"
  directory: "/"
  schedule:
    interval: "weekly"
  ignore:
    # Ignore controller-runtime as its upgraded manually.
    - dependency-name: "sigs.k8s.io/controller-runtime"
    # Ignore k8s and its transitives modules as they are upgraded manually
    # together with controller-runtime.
    - dependency-name: "k8s.io/*"
    # Ignore wrangler
    - dependency-name: "github.com/rancher/wrangler"
    - dependency-name: "github.com/rancher/wrangler/v3"
    # Ignore rancher apis
    - dependency-name: "github.com/rancher/rancher/pkg/apis"
    # Ignore Google API version, due it is breaking integration
    - dependency-name: "google.golang.org/api"
  commit-message:
    prefix: ":seedling:"
  target-branch: "release-v2.7"
