name: Update GKE operator in rancher/rancher
on:
  workflow_dispatch:
    inputs:
      rancher_ref:
        description: 'Target rancher/rancher branch against which a PR will be opened'
        required: true
        default: release/v2.9
        type: choice
        options:
          - release/v2.7
          - release/v2.8
          - release/v2.9
      new_operator_version:
        description: "New operator version (e.g. 1.1.0-rc.2), do not include the 'v' prefix"
        required: true
        default: ''

env:
  OPERATOR: gke-operator

jobs:
  create-rancher-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout operator repository to invoke release script
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0
          path: ${{ env.OPERATOR }}
          persist-credentials: false
      - name: Checkout rancher/rancher
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0
          repository: rancher/rancher
          ref: ${{ github.event.inputs.rancher_ref }}
          path: rancher
          persist-credentials: false
      - name: Setup Go
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version: '1.22.*'
      - name: Set env variables
        run: |
          echo "TIMESTAMP=$(date +'%s')" >> $GITHUB_ENV
          RANCHER_REF=${{ github.event.inputs.rancher_ref }}
          echo "VERSION=${RANCHER_REF: -4}" >> $GITHUB_ENV
      - name: Create new rancher branch
        working-directory: rancher
        run: |
          git checkout -b ${{ env.OPERATOR }}-$VERSION-$TIMESTAMP
      - name: Run release script
        run: ./${{ env.OPERATOR }}/.github/scripts/update-rancher-dep.sh ${{ github.event.inputs.new_operator_version }}
      - name: Create remote branch
        env:
          GITHUB_TOKEN: ${{ secrets.CI_BOT_TOKEN }}
        working-directory: rancher
        run: |
          git remote add bot https://${GITHUB_TOKEN}@github.com/highlander-ci-bot/rancher.git
          git push bot HEAD:${{ env.OPERATOR }}-$VERSION-$TIMESTAMP
      - name: Create PR
        env:
          GH_TOKEN: ${{secrets.CI_BOT_TOKEN}}
        run: |
          gh pr create \
            --repo rancher/rancher \
            --base "${{ github.event.inputs.rancher_ref }}" \
            --head "highlander-ci-bot:${{ env.OPERATOR }}-$VERSION-$TIMESTAMP" \
            --title "[${{ github.event.inputs.rancher_ref }}] Update ${{ env.OPERATOR }} to v${{ github.event.inputs.new_operator_version }}" \
            --body "Update operator to v${{ github.event.inputs.new_operator_version }}. Changelog: https://github.com/rancher/${{ env.OPERATOR }}/releases/tag/v${{ github.event.inputs.new_operator_version }}. cc @rancher/highlander"